graph TD
    B("fa:fa-university Data collected at the scanner   .")
    B-->C("fa:fa-users Data inspection and review   .")
    C-->D("fa:fa-laptop Curation schema design   .")
    D-->E("fa:fa-cog Schema implementation   .")
    E-->F("fa:fa-download Review & export curated data   .");
